version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - yavorfingarov
    groups:
      main:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    assignees:
      - yavorfingarov
    groups:
      main:
        patterns:
          - "*"
