name: PR renamer

on:
  pull_request:
    branches: [ master ]

permissions:
  pull-requests: write

jobs:
  rename:
    name: Rename
    runs-on: ubuntu-latest
    if: ${{ github.actor = "dependabot[bot]" }}
    steps:
      - name: Rename PR
        run: gh pr edit ${{ github.event.pull_request.number }} --title "Updated dependencies"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
